FROM reg.docker.alibaba-inc.com/ali/os:6u2
MAINTAINER shiyun.wxm "shiyun.wxm@taobao.com"  

#RUN yum -y install automake libtool libreadline-dev zlib1g-dev uuid-dev libgoogle-perftools-dev gcc-c++ wget     

#安装5.5的mysql  
#RUN yum -y --enablerepo=remi install mysql mysql-server mysql.x86_64 mysql-devel.x86_64  
   
#RUN yum -y install make automake zlib-devel readline-devel ncurses-devel.x86_64 ncurses.x86_64 subversion  
#RUN svn checkout -r 18 http://code.taobao.org/svn/tb-common-utils/trunk/ ~/tb-common-utils  
#RUN export TBLIB_ROOT=/usr/local/tb/lib && cd ~/tb-common-utils/ && chmod +x *.sh && ./build.sh  
#RUN svn checkout http://code.taobao.org/svn/tfs/tags/release-2.2.10 ~/tfs-2.2.10  
#RUN export TBLIB_ROOT=/usr/local/tb/lib && cd ~/tfs-2.2.10/ && chmod +x *.sh && ./build.sh init && ./configure --prefix=/usr/local/tfs --without-tcmalloc && make && make install  
